language: cpp
compiler: gcc

addons:
  apt:
    packages:
    - cmake
    - lcov

before_install:
- wget https://raw.githubusercontent.com/catchorg/Catch2/master/single_include/catch2/catch.hpp
- sudo mv catch.hpp /usr/include

script:
- cmake . -DENABLE_COVERAGE:BOOL=TRUE
- make
- ./BigInt

after_success:
# Create lcov report
# capture coverage info
- lcov --directory . --capture --output-file coverage.info
# filter out system and extra files.
# To also not include test code in coverage add them with full path to the patterns: '*/tests/*'
- lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' 'testing/*' --output-file coverage.info
# output coverage data for debugging (optional)
- lcov --list coverage.info
# Uploading to CodeCov
# '-f' specifies file(s) to use and disables manual 
# coverage gathering and file search which has already been done above
- bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"